<#1>
<?php
require_once('./Customizing/global/plugins/Services/Repository/RepositoryObject/Learnplaces/vendor/autoload.php');

\SRAG\Learnplaces\persistence\entity\AccordionBlock::installDB();
\SRAG\Learnplaces\persistence\entity\AccordionBlockMember::installDB();
\SRAG\Learnplaces\persistence\entity\Answer::installDB();
\SRAG\Learnplaces\persistence\entity\AudioBlock::installDB();
\SRAG\Learnplaces\persistence\entity\Block::installDB();
\SRAG\Learnplaces\persistence\entity\Comment::installDB();
\SRAG\Learnplaces\persistence\entity\CommentBlock::installDB();
\SRAG\Learnplaces\persistence\entity\Configuration::installDB();
\SRAG\Learnplaces\persistence\entity\ExternalStreamBlock::installDB();
\SRAG\Learnplaces\persistence\entity\FeedbackBlock::installDB();
\SRAG\Learnplaces\persistence\entity\HorizontalLineBlock::installDB();
\SRAG\Learnplaces\persistence\entity\ILIASLinkBlock::installDB();
\SRAG\Learnplaces\persistence\entity\Learnplace::installDB();
\SRAG\Learnplaces\persistence\entity\LearnplaceConstraint::installDB();
\SRAG\Learnplaces\persistence\entity\Location::installDB();
\SRAG\Learnplaces\persistence\entity\MapBlock::installDB();
\SRAG\Learnplaces\persistence\entity\Picture::installDB();
\SRAG\Learnplaces\persistence\entity\PictureBlock::installDB();
\SRAG\Learnplaces\persistence\entity\PictureGalleryEntry::installDB();
\SRAG\Learnplaces\persistence\entity\RichTextBlock::installDB();
\SRAG\Learnplaces\persistence\entity\VideoBlock::installDB();
\SRAG\Learnplaces\persistence\entity\Visibility::installDB();
\SRAG\Learnplaces\persistence\entity\VisitJournal::installDB();
?>